# Generated by Django 4.2.11 on 2024-06-07 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='subtitle_bottom',
            field=models.CharField(default='', max_length=24),
        ),
        migrations.AlterField(
            model_name='banner',
            name='subtitle',
            field=models.CharField(max_length=24),
        ),
    ]
