# Generated by Django 4.2.11 on 2024-06-14 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_hotelresortimg'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='facility/')),
            ],
        ),
        migrations.CreateModel(
            name='FacilityImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='facility/')),
            ],
        ),
        migrations.RemoveField(
            model_name='facility',
            name='city',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='street',
        ),
        migrations.AddField(
            model_name='facility',
            name='icon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.facilityicon'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.facilityimg'),
        ),
    ]
