# Generated by Django 4.2.11 on 2024-06-08 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_banner_subtitle_bottom_alter_banner_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerimg',
            name='image',
            field=models.ImageField(upload_to='banner/'),
        ),
    ]
