# Generated by Django 4.2.11 on 2024-06-26 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_tags_remove_blog_category_blog_tags_blog_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='data',
            new_name='date',
        ),
    ]
