# Generated by Django 4.2.11 on 2024-06-14 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_facilityicon_facilityimg_remove_facility_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facility',
            name='description',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='subtitle',
        ),
    ]
