# Generated by Django 4.2.11 on 2024-06-17 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_facility_description_remove_facility_subtitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeesImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='employe')),
            ],
        ),
        migrations.RemoveField(
            model_name='manager',
            name='image',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='testimonial',
        ),
        migrations.AddField(
            model_name='manager',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.employees'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.employeesimg'),
        ),
    ]
