# Generated by Django 4.2.11 on 2024-06-18 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_employeesimg_remove_manager_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='video',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='employeesimg',
            name='image',
            field=models.ImageField(upload_to='employee'),
        ),
    ]
