# Generated by Django 4.2.11 on 2024-06-18 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_manager_video_alter_employeesimg_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='manager/')),
            ],
        ),
        migrations.AlterField(
            model_name='employeesimg',
            name='image',
            field=models.ImageField(upload_to='employee/'),
        ),
        migrations.AddField(
            model_name='manager',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.managerimg'),
        ),
    ]
