# Generated by Django 4.2.11 on 2024-06-20 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_facility_category_facility_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facility',
            name='category',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='description',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='display',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='subtitle',
        ),
        migrations.CreateModel(
            name='FacilitySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='', max_length=32)),
                ('subtitle', models.CharField(default='', max_length=48)),
                ('description', models.CharField(default='', max_length=255)),
                ('facility', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.facility')),
            ],
        ),
    ]
