# Generated by Django 4.2.11 on 2024-06-26 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_blogimg_categories_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogimg',
            name='image',
            field=models.ImageField(upload_to='blog/'),
        ),
    ]
