# Generated by Django 4.2.11 on 2024-06-26 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_blogimg_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='data',
            field=models.DateField(default=''),
        ),
    ]
